-- Royal Imperial AI lanzamiento oficial
-- Lanzamiento oficial: habilita acciones financieras sin forzar disponibilidad de planes.
-- La disponibilidad de R1-R8 se mantiene según la configuración del Panel Admin / base de datos.
